In [145]:

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "end_to_end_project"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)
os.makedirs(IMAGES_PATH, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

In [146]:
import pandas as pd

test= pd.read_csv(r"C:\Users\alesi\Documents\group_project_ml\test.csv")
train= pd.read_csv(r"C:\Users\alesi\Documents\group_project_ml\train.csv")

In [147]:
financial_train = train.drop("y", axis=1) # drop labels for training 
y=train["y"].copy()
financial_train2 = financial_train.drop("w", axis=1)


In [148]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range = (0, 1))

fin_array = scaler.fit_transform(financial_train2)


In [149]:
features_set = np.reshape(fin_array, ( fin_array.shape[0],fin_array.shape[1],1))

In [150]:
features_set


array([[[0.77543941],
        [0.73641688],
        [0.66819053],
        ...,
        [0.81500202],
        [0.80270631],
        [0.70407194]],

       [[0.76573625],
        [0.69986236],
        [0.62592815],
        ...,
        [0.85070807],
        [0.82899471],
        [0.84460308]],

       [[0.7421511 ],
        [0.7122393 ],
        [0.76833876],
        ...,
        [0.61630346],
        [0.62767519],
        [0.68464607]],

       ...,

       [[0.84564578],
        [0.83921647],
        [0.83300523],
        ...,
        [0.78301731],
        [0.77935849],
        [0.78419072]],

       [[0.79846584],
        [0.79272539],
        [0.79541808],
        ...,
        [0.77660452],
        [0.77457619],
        [0.78108037]],

       [[0.91306063],
        [0.90600368],
        [0.89643146],
        ...,
        [0.77566848],
        [0.7717734 ],
        [0.77295746]]])

In [151]:
features_set.shape

(7326, 50, 1)

In [152]:
from keras.models import Sequential
from keras.layers import Dense, Activation, TimeDistributed, RepeatVector
from keras.layers import LSTM, GRU
from keras.layers import Dropout
from keras.callbacks import EarlyStopping

In [153]:
early_stopping = EarlyStopping(monitor="val_loss",
    min_delta=0.004, 
    patience=10, 
    restore_best_weights=True,
)

In [154]:
labels=np.array(y)
labels
labels.shape


(7326,)

In [165]:
model = Sequential()

model.add(LSTM(units=50, activation="relu", return_sequences="True" ,input_shape=(features_set.shape[1], 1)))
model.add(Dropout(0.2))

model.add(LSTM(units=50, activation="relu", return_sequences="True" ,input_shape=(features_set.shape[1], 1)))
model.add(Dropout(0.2))

model.add(LSTM(units=50, activation="relu", input_shape=(features_set.shape[1], 1)))
model.add(Dropout(0.2))


model.add(Dense(100, activation="relu"))
model.add(Dense(units = 1))
model.compile(optimizer = 'adam', loss = 'mean_squared_error')
model.fit(features_set, labels, epochs = 20,validation_split=0.2, batch_size = 32)

Epoch 1/20
184/184 [==============================] - 10s 40ms/step - loss: 0.5157 - val_loss: 0.2764
Epoch 2/20
184/184 [==============================] - 7s 38ms/step - loss: 0.1871 - val_loss: 0.2929
Epoch 3/20
184/184 [==============================] - 7s 39ms/step - loss: 0.1313 - val_loss: 0.1438
Epoch 4/20
184/184 [==============================] - 7s 38ms/step - loss: 0.1242 - val_loss: 0.1368
Epoch 5/20
184/184 [==============================] - 7s 39ms/step - loss: 0.0949 - val_loss: 6.7161
Epoch 6/20
184/184 [==============================] - 7s 38ms/step - loss: 0.0908 - val_loss: 0.3117
Epoch 7/20
184/184 [==============================] - 7s 39ms/step - loss: 0.0912 - val_loss: 0.1689
Epoch 8/20
184/184 [==============================] - 7s 38ms/step - loss: 0.0782 - val_loss: 0.1900
Epoch 9/20
184/184 [==============================] - 7s 40ms/step - loss: 0.0750 - val_loss: 41.0262
Epoch 10/20
184/184 [==============================] - 8s 42ms/step - loss: 0.0640 - val_

In [167]:

model.fit(features_set, labels, epochs = 50,validation_split=0.1, batch_size = 3663, callbacks=[early_stopping])


Epoch 1/50
2/2 [==============================] - 4s 2s/step - loss: 0.0448 - val_loss: 0.0448
Epoch 2/50
2/2 [==============================] - 4s 2s/step - loss: 0.0449 - val_loss: 0.0452
Epoch 3/50
2/2 [==============================] - 4s 2s/step - loss: 0.0442 - val_loss: 0.0448
Epoch 4/50
2/2 [==============================] - 4s 2s/step - loss: 0.0438 - val_loss: 0.0438
Epoch 5/50
2/2 [==============================] - 4s 2s/step - loss: 0.0437 - val_loss: 0.0431
Epoch 6/50
2/2 [==============================] - 4s 2s/step - loss: 0.0427 - val_loss: 0.0433
Epoch 7/50
2/2 [==============================] - 4s 2s/step - loss: 0.0435 - val_loss: 0.0436
Epoch 8/50
2/2 [==============================] - 4s 2s/step - loss: 0.0430 - val_loss: 0.0442
Epoch 9/50
2/2 [==============================] - 4s 2s/step - loss: 0.0423 - val_loss: 0.0447
Epoch 10/50
2/2 [==============================] - 4s 2s/step - loss: 0.0424 - val_loss: 0.0447
Epoch 11/50
2/2 [==============================] 

In [49]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

def build_classifier(optimizer):
    grid_model = Sequential()
    grid_model.add(LSTM(units = 64,input_shape = (50,1)))
    grid_model.add(Dropout(0.4))
    grid_model.add(Dense(1))

    grid_model.compile(loss = 'mse',optimizer = optimizer, metrics = ['mean_squared_error'])
    return grid_model

grid_model = KerasClassifier(build_fn=build_classifier)
parameters = {'batch_size' : [32],
               'epochs' : [20,50],
              'optimizer' : ['adam'] }

grid_search  = GridSearchCV(estimator = grid_model,
                            param_grid = parameters,
                            scoring = 'neg_mean_squared_error',
                            cv = 2)



grid_search = grid_search.fit(features_set,labels)

Epoch 1/20
115/115 [==============================] - 9s 34ms/step - loss: 4436222.5388 - mean_squared_error: 4436222.5388 1s - loss: 4432306
Epoch 2/20
115/115 [==============================] - 4s 37ms/step - loss: 4387077.6681 - mean_squared_error: 4387077.6681
Epoch 3/20
115/115 [==============================] - 4s 36ms/step - loss: 4502448.5948 - mean_squared_error: 4502448.5948
Epoch 4/20
115/115 [==============================] - 4s 37ms/step - loss: 4358095.1487 - mean_squared_error: 4358095.1487
Epoch 5/20
115/115 [==============================] - 4s 37ms/step - loss: 4323647.3922 - mean_squared_error: 4323647.3922
Epoch 6/20
115/115 [==============================] - 4s 38ms/step - loss: 4328464.3297 - mean_squared_error: 4328464.3297
Epoch 7/20
115/115 [==============================] - 4s 39ms/step - loss: 4268598.1228 - mean_squared_error: 4268598.1228
Epoch 8/20
115/115 [==============================] - 4s 39ms/step - loss: 4176462.4095 - mean_squared_error: 4176462.40

C:\Users\alesi\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Epoch 1/50
115/115 [==============================] - 9s 35ms/step - loss: 4410328.5043 - mean_squared_error: 4410328.5043 1s -
Epoch 2/50
115/115 [==============================] - 4s 35ms/step - loss: 4282726.0366 - mean_squared_error: 4282726.0366
Epoch 3/50
115/115 [==============================] - 4s 36ms/step - loss: 4525169.5819 - mean_squared_error: 4525169.5819
Epoch 4/50
115/115 [==============================] - 4s 36ms/step - loss: 4346491.5970 - mean_squared_error: 4346491.5970 1s -
Epoch 5/50
115/115 [==============================] - 4s 37ms/step - loss: 4275080.9871 - mean_squared_error: 4275080.9871
Epoch 6/50
115/115 [==============================] - 4s 38ms/step - loss: 4215660.7241 - mean_squared_error: 4215660.7241
Epoch 7/50
115/115 [==============================] - 5s 39ms/step - loss: 4369508.8233 - mean_squared_error: 4369508.8233
Epoch 8/50
115/115 [==============================] - 4s 37ms/step - loss: 4266957.3750 - mean_squared_error: 4266957.3750
Epoch 

C:\Users\alesi\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Epoch 1/50
115/115 [==============================] - 9s 34ms/step - loss: 4485721.7866 - mean_squared_error: 4485721.7866
Epoch 2/50
115/115 [==============================] - 4s 34ms/step - loss: 4406261.2953 - mean_squared_error: 4406261.2953
Epoch 3/50
115/115 [==============================] - 4s 34ms/step - loss: 4520476.7500 - mean_squared_error: 4520476.7500
Epoch 4/50
115/115 [==============================] - 4s 37ms/step - loss: 4290460.8944 - mean_squared_error: 4290460.8944
Epoch 5/50
115/115 [==============================] - 4s 33ms/step - loss: 4361838.4397 - mean_squared_error: 4361838.4397
Epoch 6/50
115/115 [==============================] - 4s 34ms/step - loss: 4319751.8534 - mean_squared_error: 4319751.8534
Epoch 7/50
115/115 [==============================] - 4s 34ms/step - loss: 4224164.8233 - mean_squared_error: 4224164.8233
Epoch 8/50
115/115 [==============================] - 4s 35ms/step - loss: 4277768.3103 - mean_squared_error: 4277768.3103
Epoch 9/50
115/1

C:\Users\alesi\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Epoch 1/20
229/229 [==============================] - 15s 37ms/step - loss: 17465882.0652 - mean_squared_error: 17465882.0652
Epoch 2/20
229/229 [==============================] - 9s 37ms/step - loss: 17880950.7304 - mean_squared_error: 17880950.7304
Epoch 3/20
229/229 [==============================] - 8s 37ms/step - loss: 17637647.8261 - mean_squared_error: 17637647.8261
Epoch 4/20
229/229 [==============================] - 9s 38ms/step - loss: 17460558.9739 - mean_squared_error: 17460558.9739
Epoch 5/20
229/229 [==============================] - 9s 38ms/step - loss: 17485524.1739 - mean_squared_error: 17485524.1739
Epoch 6/20
229/229 [==============================] - 9s 38ms/step - loss: 17532345.8174 - mean_squared_error: 17532345.8174
Epoch 7/20
229/229 [==============================] - 9s 38ms/step - loss: 17187638.7522 - mean_squared_error: 17187638.7522
Epoch 8/20
229/229 [==============================] - 8s 37ms/step - loss: 17003777.5565 - mean_squared_error: 17003777.5565

In [50]:
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_
best_parameters

{'batch_size': 32, 'epochs': 20, 'optimizer': 'adam'}

In [38]:

test_scaled=scaler.transform(test)
test_scaled


array([[0.2234717 , 0.16163201, 0.20019499, ..., 0.42314219, 0.39647356,
        0.38653022],
       [0.54778469, 0.53651845, 0.59138859, ..., 0.64188457, 0.57389185,
        0.54498805],
       [0.81151686, 0.75810207, 0.75106067, ..., 0.7945658 , 0.83358227,
        0.91174531],
       ...,
       [0.96338652, 0.95140427, 0.94364447, ..., 0.76946144, 0.76684189,
        0.77329558],
       [0.78042029, 0.78092329, 0.77810149, ..., 0.79887116, 0.79436882,
        0.79631411],
       [0.87834256, 0.87097847, 0.86740449, ..., 0.79194238, 0.78574633,
        0.7925877 ]])

In [39]:

test_features = np.reshape(test_scaled, (-1, test_scaled.shape[1], 1))
test_features.shape


test_features.shape

(3141, 50, 1)

In [159]:
predictions = model.predict(test_features)
predictions

array([[-0.43264723],
       [ 0.28264827],
       [ 1.5591255 ],
       ...,
       [ 1.0240332 ],
       [ 1.0181649 ],
       [ 1.0232127 ]], dtype=float32)

In [163]:
np.savetxt("submissions23.txt", predictions,delimiter = ",")